name: Pull Request Check

on: pull_request

jobs:
  check:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: pnpm cache
        uses: actions/cache@v2
        with:
          path: ./common/temp/pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('common/config/rush/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-

      - name: Install
        run: node common/scripts/install-run-rush.js install

      - name: Check dependencies
        run: node common/scripts/install-run-rush.js check

      - name: Verify change files
        run: node common/scripts/install-run-rush.js change --verify
