name: Deploy Tracker

on:
  push:
    tags: 
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy:
    runs-on: ubuntu-20.04

    env:
      NPM_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: pnpm cache
        uses: actions/cache@v2
        with:
          path: ./common/temp/pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('common/config/rush/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-

      - name: Install
        run: node common/scripts/install-run-rush.js install

      - name: Build
        run: node common/scripts/install-run-rush.js rebuild --verbose

      - name: Setup git
        uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Version
        run: node common/scripts/install-run-rush.js version --bump --target-branch main

      - name: Publish
        run: node common/scripts/install-run-rush.js publish --apply --include-all --publish --target-branch main --set-access-level public

      - name: Get Version Information
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Zip release
        run: zip -r release.zip ./libraries/**/dist/*.js

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: v${{ steps.get_version.outputs.version }}
          files: ./release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
