name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The release tag'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-20.04

    env:
      NPM_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: pnpm cache
        uses: actions/cache@v2
        with:
          path: ./common/temp/pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('common/config/rush/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-

      - name: Install
        run: node common/scripts/install-run-rush.js install

      - name: Setup git
        uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          name: github-actions[bot]
          email: 41898282+github-actions[bot]@users.noreply.github.com

      - name: Version
        run: node common/scripts/install-run-rush.js version --bump --target-branch main

      - name: Get tag and tracker version information
        id: version
        run: echo "##[set-output name=TRACKER_VERSION;]$(node -p "require('./libraries/add/package.json').version")"
      
      - name: Fail if version mismatch
        if: ${{ github.event.inputs.version != steps.version.outputs.TRACKER_VERSION }}
        run: |
          echo "Input version (${{ github.event.inputs.version }}) doesn't match version in project (${{ steps.version.outputs.TRACKER_VERSION }})"
          exit 1

      - name: Build
        run: node common/scripts/install-run-rush.js rebuild --verbose
        
      - name: Publish
        run: node common/scripts/install-run-rush.js publish --apply --include-all --publish --target-branch main --set-access-level public

      - name: Zip release
        run: zip -r release.zip ./libraries/**/dist/*.js

      - name: Generate Changelog
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.3
        with:
          dry_run: true
          tag_prefix: ''
          default_bump: false
          custom_tag: ${{ github.event.inputs.version }}
      
      - name: Tag release
        run: |
          git tag -a ${{ steps.tag_version.outputs.new_tag }} -m "Version ${{ steps.tag_version.outputs.new_tag }}"
          git push --tags

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Version ${{ steps.tag_version.outputs.new_tag }}
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          files: ./release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
